name: marvel_heroes
description: A Marvel Heroes App

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  awesome_stepper: ^0.1.3
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.3+2
  lib_msaadev:
    git:
      url: https://github.com/msaadev/lib_msaadev
  mobx: ^2.0.6+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:

  color: "#ee2323"

  image: "assets/images/marvel.png"

  android_gravity: center

  ios_content_mode: center
